### ISSUE TITLE
Constructor Method in Node class that accepts a node link and  a asset object.

### ISSUE THREAD

**Issue by ricardogaynorgaynor** [gggordon/stacks-queues-asset-example#1]
How will this constructor be useful that i saw in the Node class ?

public Node(Asset data, Node link) {
		super();
		this.data = data;
		this.link = link;
}

**Comment by gggordon** [comment]
Constructor overloads are included for convenience. In the event that another programmer would like to initialize both the Asset data and link reference at the same time, they could use this method.

Eg.
```
Asset asset2  = new Asset();
Node node2 = new Node(asset2);

Asset asset1  = new Asset();
Node node1 = new Node(asset1, node2);

```

Now, visually this looks like this
```
Node 1 [ Asset 1 ]---> Node 2 [Asset2]

```

Constructors are created to allow us to initialize object state during creation and various overloads of primary constructors allow us the convenience of specifying what we would need to initialize
